@startchen cineplanet
entity Ciudad {
    id_ciudad : INT <<key>>
    nombre : STRING
}
entity Cine {
    id_ciudad : INT FK
    id_cine : INT <<key>>
}
entity Sala {
    id_sala : INT <<key>>
    filas : INT
    columnas : INT
}
entity Asiento {
    id_sala : INT FK
    fila : INT PK
    columna : INT PK
}
entity FuncionAsiento {
    id_funcion : INT FK
    fila : INT PK
    columna : INT PK
    estado : INT FK
}
entity Dulceria {
}
entity Categoria {
}
entity Dulce {
}
entity Pelicula {
}
entity Funcion {
    id_funcion : INT PK
    hora_inicio : STRING
    id_sala : INT FK
    id_pelicula : INT FK
}
entity Cliente {
    nombre : STRING
    id_funcion : INT PK
    dni : STRING
    id_funcion_asiento : INT PK
}
entity Miembro {
}
entity Personal {
}
entity Funcion_sala {
}
@endchen