@startchen cineplanet
entity Ciudad {
idciudad : INT <<key>>
nombre : STRING
}
entity Cine {
idcine : INT <<key>>
}
entity Sala {
}
entity Asiento {
}
entity Dulceria {
}
entity Categoria {
}
entity Dulce {
}
entity Pelicula {
}
entity Funcion {
}
entity Persona {
}
entity Miembro {
}
entity Personal {
}
entity Funcion_sala {
}
@endchen