@startchen cineplanet
entity Ciudad {
    idciudad : INT <<key>>
    nombre : STRING
}
entity Cine {
    idcine : INT <<key>>
}
entity Sala {
    idsala : INT <<key>>
    filas : INT
    columnas : INT
}
entity Asiento {
    idsala : INT FK
    fila : INT PK
    columna : INT PK
}
entity AsientoSala {
}
entity Dulceria {
}
entity Categoria {
}
entity Dulce {
}
entity Pelicula {
}
entity Funcion {
}
entity Persona {
}
entity Miembro {
}
entity Personal {
}
entity Funcion_sala {
}
@endchen